### ISSUE TITLE
Wrong User for Recurring Payment

### ISSUE THREAD

**Issue by wrought** [sudoroom/sudo-humans#20]
Upon first sign up, I clicked the link on the "welcome" page (https://sudoroom.org/humans/account/welcome) that says "set up **recurring payments**" but that link did not direct me to the proper url (my user name is wrought), instead it directed me to the following link:

https://sudoroom.org/humans/~ashleyq007/payment

Not sure if these means my payment will be associated with a pseudonym, or the wrong account, or perhaps is not an issue, but merely an improper route for the same proper function.

**Comment by Juul** [comment]
Thanks! It didn't actually affect anything other than the URL being wrong, but it is now fixed.
