### ISSUE TITLE
Check that emails are being sent for password reset

### ISSUE THREAD

**Issue by wrought** [sudoroom/sudo-humans#24]
Ed reported that previous attempts to reset his password for his user account "Edlardo" but it might be a user error, we should check that the feature works, and see if there have been any logged errors or email messages queued on the server.

**Comment by rcsheets** [comment]
I just tried a password reset by submitting my username, and I received a password reset email as expected.

**Comment by rcsheets** [comment]
Also works fine when I submit my email address.

**Comment by jnny** [comment]
May be due to the fact that usernames are case sensitive. See also Issue #48
