### ISSUE TITLE
case-sensitive username is jamming people up!

### ISSUE THREAD

**Issue by jerkey** [sudoroom/sudo-humans#34]
myself and jenny were both locked out for several days because we didn't realize that the username is case-sensitive.

my preference would be to eliminate case-sensitivity in logins and account creation (for obvious reasons) but at the VERY LEAST the login window should remind you that your login is case-sensitive.

also, when you do a password reset, it asks your email address - but what if you don't remember your pseudonym!?!?!?  it does not remind you in the email, and you can't use your email address to log in!

**Comment by yardenac** [comment]
This is fixed in the code (though not yet deployed).
