### ISSUE TITLE
is "~" unintuitive?

### ISSUE THREAD

**Issue by wrought** [sudoroom/sudo-humans#4]
I like the simple user directory throwback, and it helps prevent users from co-opting a URL based on user name (e.g. sudoroom.org/humans/mustdie is instead sudoroom.org/humans/~mustdie)

on the other hand, the url then becomes unintuitive, a bit ugly, and may be confusing for new users who might confuse "~username" with "username" and not realize which in fact is their username and what the "~" is supposed to mean.

**Comment by ghost** [comment]
I think it is not too much of a problem given our audience for sudoroom although the omni might be a different matter. Perhaps this can hide under a config option later `{ hackerDisplay: true }`

**Comment by wrought** [comment]
Closing for now
