### ISSUE TITLE
write migration script to move a live instance from single-collective to multi-collective operation

### ISSUE THREAD

**Issue by Juul** [sudoroom/sudo-humans#40]

**Comment by wrought** [comment]
How do you think this will affect the choices I outlined in #33?

**Comment by Juul** [comment]
it won't :)

**Comment by yardenac** [comment]
looks like marc fixed it https://github.com/sudoroom/sudo-humans/commit/fbb7e3f2c3a7fbdff0a0cfe527aed029fe0e5ce4
