### ISSUE TITLE
rollback to single-collective version

### ISSUE THREAD

**Issue by wrought** [sudoroom/sudo-humans#44]
@Juul I need to hear that you are planning to finish what you've started, or that there's some other compelling reason for me to wait, otherwise I'm going to roll back `master` to before the multi-collective changes.

This is why feature branches and pull-requests exist, and I'm irritated because this has held up my #33 refactoring of the Stripe code to handle different payment frequencies and amounts (based on additional fees/costs). I've sat down three times to try to work on the code as it is and incorporate the changes I had already started making, and by now I've wasted a lot of time just trying to understand how you've started changing the app (and yes it does actually affect the code I was re-writing).

@substack even suggests writing something new based on sudo-humans instead of frankensteining this app.

**Comment by yardenac** [comment]
I did this a couple weeks ago. Created 3 branches:

https://github.com/sudoroom/sudo-humans/commits/master <-- removed commits with rebase, push -f
https://github.com/sudoroom/sudo-humans/commits/multicollective <-- in-progress stuff
https://github.com/sudoroom/sudo-humans/commits/fuckedup <-- original master preserved

**Comment by yardenac** [comment]
Just for the record - multicollective branch has since been fixed, deployed and merged to master.
