### ISSUE TITLE
title line for CCL collective still reads "sudo room"

### ISSUE THREAD

**Issue by PatrikD** [sudoroom/sudo-humans#50]
When I go to the page for the Counter Culture Labs collective, the title line at the top of the web page still reads "/ collectives / sudo room"

See: https://sudoroom.org/humans/c/ccl

This is causing a lot of confusion with our CCL members because it looks like they're signing up for the wrong organization.

**Comment by hackergrrl** [comment]
PR to address this: https://github.com/sudoroom/sudo-humans/pull/57
