### ISSUE TITLE
Clearer CTA to set up membership

### ISSUE THREAD

**Issue by stackptr** [sudoroom/sudo-humans#71]
Hey y'all

It took a good amount of poking around in /humans before I finally figured out that I needed to edit my profile and set up a membership that way.

I would expect to be able to do this via the collective page. I think it would be fairly straightforward to show an alert similar to the one asking to administer the collective (which I shouldn't see if I'm not an admin, but that's another topic), noting that I have not set up membership and providing a link to the appropriate edit route

If this makes sense I can code it fairly quick and set up a PR

**Comment by Juul** [comment]
Yes definitely makes sense! That would a be a great contribution :+1:

**Comment by rcsheets** [comment]
I like this idea a lot.

**Comment by stackptr** [comment]
Opened PR #72 to address
